---

# TODO: this assumes nebula_lighthouse_hostname is the same as the ansible inventory name
- name: Set FQDN for each host
  set_fact:
    local_fqdn: "{{ nebula_lighthouse_hostname }}.{{ nebula_fqdn }}"

- name: Get lighthouse keys from localhost
  copy:
    src: "{{key_location}}/{{ local_fqdn }}.{{ item }}"
    dest: /opt/nebula/{{ local_fqdn }}.{{ item }}
  loop:
    - crt
    - key

- name: Get ca cert from localhost
  copy:
    src: "{{key_location}}/ca.crt"
    dest: /opt/nebula/ca.crt

- name: Ensure lighthouse is configured
  template:
    src: lighthouse_config.yml.j2 
    dest: /opt/nebula/config.yml
    owner: root
    group: root
    mode: '0400'
  notify: restart nebula

- name: Ensure lighthouse service exists
  template:
    src: lighthouse.service.j2
    dest: /etc/systemd/system/lighthouse.service
    owner: root
    group: root
    mode: '0644'

# We want to restart to pick up the dns config settings
- name: Ensure lighthouse service is enabled and running
  systemd: 
    name: lighthouse
    daemon_reload: yes
    enabled: yes
    masked: no
    state: restarted
