---

# TODO: this assumes a lot about the inventory_hostname and the certificate details
- name: Set FQDN for each host
  set_fact:
    local_fqdn: "{{ inventory_hostname }}.{{ nebula_fqdn }}"

- name: Get lighthouse keys from localhost
  copy:
    src: "{{ local_fqdn }}.{{ item }}"
    dest: "{{ nebula_install_destination}}/{{ local_fqdn }}.{{ item }}"
  loop:
    - crt
    - key

- name: Get ca cert from localhost
  copy:
    src: "ca.crt"
    dest: "{{ nebula_install_destination}}/ca.crt"

- name: Ensure lighthouse is configured
  template:
    src: lighthouse_config.yml.j2 
    dest: "{{ nebula_install_destination}}/config.yml"
    owner: root
    group: root
    mode: '0400'
  notify: restart nebula

- name: Ensure lighthouse service exists
  template:
    src: lighthouse.service.j2
    dest: /etc/systemd/system/lighthouse.service
    owner: root
    group: root
    mode: '0644'

# We want to restart to pick up the dns config settings
- name: Ensure lighthouse service is enabled and running
  systemd: 
    name: lighthouse
    daemon_reload: yes
    enabled: yes
    masked: no
    state: restarted
