---
- name: Nebula Install
  block:
    - name: Uninstall Nebula (clean install)
      include_tasks: uninstall.yml
      when: nebula_clean_install|bool
    
    - name: Install Nebula on all hosts 
      include_tasks: nebula.yml
    
    - name: Deploy Lighthouse
      include_tasks: lighthouse.yml
      when: inventory_hostname in nebula_lighthouses_inventory
    
    - name: Deploy Nebula Node
      include_tasks: node.yml
      when: inventory_hostname not in nebula_lighthouses_inventory
  when: inventory_hostname in nebula_lighthouses_inventory or nebula_internal_ip_addr is defined
