- name: Set FQDN for each host
  set_fact:
    local_fqdn: "{{ inventory_hostname }}.{{ nebula_fqdn }}"

- name: Get lighthouse keys from localhost
  copy:
    src: "{{ local_fqdn }}.{{ item }}"
    dest: "{{ nebula_install_destination}}/{{ local_fqdn }}.{{ item }}"
  loop:
    - crt
    - key

- name: Get ca cert from localhost
  copy:
    src: "ca.crt"
    dest: "{{ nebula_install_destination}}/ca.crt"

- name: Ensure node has hosts file entry for lighthouse
  lineinfile:
    path: /etc/hosts
    line: "{{ item.overlay_addr }} {{ item.inventory }}.{{ nebula_fqdn }}"
  loop: "{{ nebula_lighthouses }}"
  when: nebula_node_lighthouse_in_hosts_file

- name: Ensure Nebula is configured
  template:
    src: node_config.yml.j2 
    dest: "{{ nebula_install_destination}}/config.yml"
    owner: root
    group: root
    mode: '0400'
  notify: restart nebula

- name: Ensure Nebula service exists
  template:
    src: node.service.j2
    dest: /etc/systemd/system/nebula.service
    owner: root
    group: root
    mode: '0644'

- name: Ensure Nebula service is enabled and running
  systemd: 
    name: nebula
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started

- name: Ensure nebula-check is present
  template:
    src: nebula-check.sh.j2
    dest: "{{ nebula_install_destination}}/nebula-check.sh"
    owner: root
    group: root
    mode: '0755'
  when: nebula_install_check_cron|bool

- name: Ensure nebula-check is scheduled via cron
  cron:
    name: "nebula-check"
    minute: "{{ nebula_check_cron_minute | default('*/5') }}"
    job: "{{ nebula_install_destination}}/nebula-check.sh"
  when: nebula_install_check_cron|bool

- name: Add systemd-networkd template for using overlay dns
  template:
    src: nebula_dns.network.j2
    dest: /etc/systemd/network/{{ nebula_interface_name }}.network
    owner: root
    group: root
    mode: '0644'

- name: Restart systemd-networkd to get our dns resolution
  service:
    name: systemd-networkd
    state: restarted
