- name: Restart Nebula
  systemd:
    name: nebula
    state: restarted
  when: inventory_hostname not in (nebula_lighthouses | map(attribute='inventory') | list) and inventory_hostname != nebula_certificate_authority
  listen: "restart nebula"

- name: Restart Lighthouse
  systemd:
    name: lighthouse
    state: restarted
  when: inventory_hostname in (nebula_lighthouses | map(attribute='inventory') | list) and inventory_hostname != nebula_certificate_authority
  listen: "restart nebula"
